#!/bin/sh
# darkman hook: use Gruvbox GTK only in the dark solar state.
set -e

DARK_FALLBACK_THEME="Adwaita-dark"
LIGHT_THEME="Adwaita"

theme_exists() {
  theme="$1"
  [ -d "$HOME/.themes/$theme" ] ||
    [ -d "$HOME/.local/share/themes/$theme" ] ||
    [ -d "/usr/local/share/themes/$theme" ] ||
    [ -d "/usr/share/themes/$theme" ]
}

first_existing_theme() {
  for theme in "$@"; do
    if theme_exists "$theme"; then
      printf '%s\n' "$theme"
      return 0
    fi
  done
  return 0
}

case "$1" in
dark)
  gtk_theme="$(first_existing_theme \
    Gruvbox-Material-Dark \
    Gruvbox-Dark-Medium \
    Gruvbox-Dark)"

  if [ -z "$gtk_theme" ]; then
    gtk_theme="$DARK_FALLBACK_THEME"
    printf '%s\n' \
      "darkman: no Gruvbox dark GTK theme installed; using $DARK_FALLBACK_THEME" >&2
  fi

  color_scheme="prefer-dark"
  ;;
light)
  gtk_theme="$LIGHT_THEME"
  color_scheme="prefer-light"
  ;;
*) exit 0 ;;
esac

gsettings set org.gnome.desktop.interface color-scheme "$color_scheme"
gsettings set org.gnome.desktop.interface gtk-theme "$gtk_theme"
