edge center-sized
kitty_override background=#282828
kitty_override foreground=#d4be98
kitty_override selection_background=#d4be98
kitty_override selection_foreground=#282828
kitty_override cursor=#a89984
kitty_override cursor_text_color=background
kitty_override color0=#665c54
kitty_override color1=#ea6962
kitty_override color2=#a9b665
kitty_override color3=#e78a4e
kitty_override color4=#7daea3
kitty_override color5=#d3869b
kitty_override color6=#89b482
kitty_override color7=#d4be98
kitty_override color8=#928374
kitty_override color9=#ea6962
kitty_override color10=#a9b665
kitty_override color11=#d8a657
kitty_override color12=#7daea3
kitty_override color13=#d3869b
kitty_override color14=#89b482
kitty_override color15=#d4be98
kitty_override tab_bar_style=hidden
lines 22
columns 90
background_opacity 0.85
