#!/usr/bin/env python3
from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
HELPER = ROOT / "helium/apply-gruvbox-theme.py"
USER_COLOR_THEME_ID = "user_color_theme_id"
EXPECTED_SEED = -12830666  # signed SkColor for #3c3836


def run_helper(home: Path, *, expect: int = 0) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env["HOME"] = str(home)
    env["XDG_CONFIG_HOME"] = str(home / ".config")
    env["XDG_DATA_HOME"] = str(home / ".local/share")
    # Match dots-state.py's isolated generator environment so process detection
    # never confuses CI with a real user's running browser.
    env["DOTS_REAL_HOME"] = "/real-user-home"
    process = subprocess.run(
        [sys.executable, str(HELPER)],
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    assert process.returncode == expect, (process.stdout, process.stderr)
    return process


def profile_path(home: Path, profile: str = "Profile 2") -> Path:
    return home / ".config/net.imput.helium" / profile / "Preferences"


def read_preferences(home: Path, profile: str = "Profile 2") -> dict:
    return json.loads(profile_path(home, profile).read_text())


def make_legacy_state(home: Path) -> None:
    config = home / ".config"
    data = home / ".local/share"
    user_data = config / "net.imput.helium"
    preferences = user_data / "Profile 2/Preferences"
    preferences.parent.mkdir(parents=True)
    (user_data / "Local State").write_text(
        json.dumps({"profile": {"last_used": "Profile 2"}})
    )
    preferences.write_text(
        json.dumps(
            {
                "unrelated": {"preserved": True},
                "browser": {
                    "theme": {
                        "color_scheme": 2,
                        "color_scheme2": 2,
                        "user_color": -1,
                        "user_color2": -1,
                        "color_variant": 3,
                        "color_variant2": 3,
                        "follows_system_colors": True,
                        "is_grayscale": True,
                        "is_grayscale2": True,
                    }
                },
                "extensions": {
                    "theme": {
                        "id": "old-extension-theme",
                        "pack": "Cached Theme.pak",
                        "colors": {"frame": [40, 40, 40]},
                        "images": {"theme_ntp_background": "old.png"},
                        "tints": {"buttons": [-1, -1, -1]},
                        "properties": {"ntp_logo_alternate": 1},
                    }
                },
                "autogenerated": {"theme": {"color": 123456}},
            }
        )
    )

    flags = config / "helium-browser-flags.conf"
    flags.parent.mkdir(parents=True, exist_ok=True)
    flags.write_text(
        "--enable-features=SomethingUseful\n"
        "--force-light-mode\n"  # legacy standalone flag: must be removed too
        "--load-extension=/tmp/user-extension,/home/test/.local/share/dotfiles/helium-gruvbox\n"
        "\n"
        "# >>> dotfiles: helium gruvbox >>>\n"
        "--load-extension=/home/./test/.local/share/dotfiles/helium-gruvbox\n"
        "# <<< dotfiles: helium gruvbox <<<\n"
        "\n"
        "# >>> dotfiles: helium web color-scheme >>>\n"
        "--force-dark-mode\n"
        "# <<< dotfiles: helium web color-scheme <<<\n"
    )

    for name in ("helium-gruvbox", "helium-gruvbox-dark", "helium-gruvbox-light"):
        directory = data / "dotfiles" / name
        directory.mkdir(parents=True)
        (directory / "manifest.json").write_text("{}\n")


def assert_native_theme(home: Path) -> None:
    preferences = read_preferences(home)
    assert preferences["unrelated"]["preserved"] is True

    theme = preferences["browser"]["theme"]
    assert theme["color_scheme"] == 0
    assert theme["color_scheme2"] == 0
    assert theme["user_color"] == EXPECTED_SEED
    assert theme["user_color2"] == EXPECTED_SEED
    assert theme["color_variant"] == 2
    assert theme["color_variant2"] == 2
    assert theme["follows_system_colors"] is False
    assert theme["is_grayscale"] is False
    assert theme["is_grayscale2"] is False

    extension_theme = preferences["extensions"]["theme"]
    assert extension_theme["id"] == USER_COLOR_THEME_ID
    for key in ("pack", "colors", "images", "tints", "properties"):
        assert key not in extension_theme
    assert "color" not in preferences.get("autogenerated", {}).get("theme", {})

    flags_path = home / ".config/helium-browser-flags.conf"
    flags = flags_path.read_text()
    assert "--enable-features=SomethingUseful" in flags
    assert "--load-extension=/tmp/user-extension" in flags
    assert "helium-gruvbox" not in flags
    assert "dotfiles: helium" not in flags
    assert "--force-light-mode" not in flags
    assert "--force-dark-mode" not in flags

    data = home / ".local/share/dotfiles"
    for name in ("helium-gruvbox", "helium-gruvbox-dark", "helium-gruvbox-light"):
        assert not (data / name).exists()


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="dots-helium-native-") as temp:
        home = Path(temp) / "home"
        home.mkdir()
        make_legacy_state(home)

        first = run_helper(home)
        assert "net.imput.helium/Profile 2/Preferences" in first.stdout
        assert "Helium adaptive theme: updated" in first.stdout
        assert "#3c3836 (neutral, system scheme)" in first.stdout
        assert_native_theme(home)

        # Applying again is a no-op for Preferences and does not recreate the
        # removed extension state.
        before = profile_path(home).read_bytes()
        second = run_helper(home)
        after = profile_path(home).read_bytes()
        assert before == after
        assert "Helium adaptive theme: unchanged" in second.stdout
        assert_native_theme(home)

    # A fresh machine may not have launched Helium yet. Cleanup still happens,
    # but the helper does not invent a browser profile.
    with tempfile.TemporaryDirectory(prefix="dots-helium-missing-") as temp:
        home = Path(temp) / "home"
        home.mkdir()
        config = home / ".config"
        data = home / ".local/share/dotfiles/helium-gruvbox"
        config.mkdir(parents=True)
        data.mkdir(parents=True)
        (data / "manifest.json").write_text("{}\n")
        (config / "helium-browser-flags.conf").write_text(
            "--force-light-mode\n"
            "# >>> dotfiles: helium gruvbox >>>\n"
            "--load-extension=/tmp/dotfiles/helium-gruvbox\n"
            "# <<< dotfiles: helium gruvbox <<<\n"
        )
        process = run_helper(home)
        assert "net.imput.helium/Default/Preferences" in process.stdout
        assert "Helium profile not found" in process.stdout
        assert not profile_path(home, "Default").exists()
        assert not (home / ".config/helium-browser-flags.conf").exists()
        assert not data.exists()

    # Never clobber a malformed active browser profile.
    with tempfile.TemporaryDirectory(prefix="dots-helium-invalid-") as temp:
        home = Path(temp) / "home"
        user_data = home / ".config/net.imput.helium"
        prefs = user_data / "Profile 1/Preferences"
        prefs.parent.mkdir(parents=True)
        (user_data / "Local State").write_text(json.dumps({"profile": {"last_used": "Profile 1"}}))
        prefs.write_text("{not json")
        process = run_helper(home, expect=1)
        assert "invalid Helium Preferences JSON" in process.stdout
        assert prefs.read_text() == "{not json"

    # Respect an explicit persistent --user-data-dir before standard locations.
    with tempfile.TemporaryDirectory(prefix="dots-helium-explicit-") as temp:
        home = Path(temp) / "home"
        custom = home / "custom-helium"
        prefs = custom / "Default/Preferences"
        prefs.parent.mkdir(parents=True)
        prefs.write_text(json.dumps({"extensions": {"theme": {}}, "browser": {"theme": {}}}))
        flags = home / ".config/helium-browser-flags.conf"
        flags.parent.mkdir(parents=True)
        flags.write_text(f"--user-data-dir={custom}\n")
        process = run_helper(home)
        assert str(prefs) in process.stdout
        configured = json.loads(prefs.read_text())
        assert configured["extensions"]["theme"]["id"] == USER_COLOR_THEME_ID
        assert f"--user-data-dir={custom}" in flags.read_text()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
