#!/usr/bin/env python3
from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import tomllib

ROOT = Path(__file__).resolve().parents[1]
APPLY = ROOT / "helium/apply-gruvbox-theme.py"
SWITCH = ROOT / "helium/switch-gruvbox-theme.py"
DARK = ROOT / "helium/gruvbox-dark/manifest.json"
LIGHT = ROOT / "helium/gruvbox-light/manifest.json"
PALETTE = ROOT / "colors.toml"


def fake_darkman(bin_dir: Path, mode: str) -> None:
    bin_dir.mkdir(parents=True, exist_ok=True)
    script = bin_dir / "darkman"
    script.write_text(f"#!/bin/sh\nprintf '%s\\n' {mode!r}\n")
    script.chmod(0o755)


def env_for(home: Path, mode: str = "dark") -> dict[str, str]:
    env = os.environ.copy()
    bin_dir = home / ".test-bin"
    fake_darkman(bin_dir, mode)
    env.update(
        {
            "HOME": str(home),
            "XDG_CONFIG_HOME": str(home / ".config"),
            "XDG_DATA_HOME": str(home / ".local/share"),
            "PATH": str(bin_dir) + os.pathsep + env.get("PATH", ""),
        }
    )
    return env


def run(command: list[str], env: dict[str, str]) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        command,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    assert result.returncode == 0, (result.stdout, result.stderr)
    return result


def runtime_manifest(home: Path) -> Path:
    return home / ".local/share/dotfiles/helium-gruvbox/manifest.json"


def rgb(value: str) -> list[int]:
    value = value.removeprefix("#")
    return [int(value[index : index + 2], 16) for index in (0, 2, 4)]


def assert_exact_palettes() -> None:
    palette = tomllib.loads(PALETTE.read_text())
    dark_palette = palette["colors"]
    light_palette = palette["colors_light"]
    dark = json.loads(DARK.read_text())["theme"]["colors"]
    light = json.loads(LIGHT.read_text())["theme"]["colors"]

    mapping = {
        "frame": "bg_hard",
        "toolbar": "bg_soft",
        "omnibox_background": "bg",
        "tab_text": "fg",
        "ntp_link": "blue",
    }
    for chromium_name, palette_name in mapping.items():
        assert dark[chromium_name] == rgb(dark_palette[palette_name])
        assert light[chromium_name] == rgb(light_palette[palette_name])

    assert dark["frame"] == [29, 32, 33]  # #1d2021
    assert dark["omnibox_background"] == [40, 40, 40]  # #282828
    assert light["frame"] == [242, 239, 232]  # #f2efe8
    assert light["omnibox_background"] == [251, 250, 247]  # #fbfaf7


def main() -> int:
    assert_exact_palettes()

    with tempfile.TemporaryDirectory(prefix="dots-helium-exact-") as temp:
        home = Path(temp) / "home"
        home.mkdir()
        env = env_for(home, "dark")

        config = home / ".config"
        config.mkdir(parents=True)
        flags = config / "helium-browser-flags.conf"
        flags.write_text(
            "--enable-features=SomethingUseful\n"
            "--force-light-mode\n"
            "--load-extension=/tmp/user-extension,/tmp/dotfiles/helium-gruvbox\n"
            "# >>> dotfiles: helium adaptive theme >>>\n"
            "--install-autogenerated-theme=60,56,54\n"
            "# <<< dotfiles: helium adaptive theme <<<\n"
        )

        # The exact-theme setup must not own or rewrite Chromium Preferences.
        prefs = config / "net.imput.helium/Default/Preferences"
        prefs.parent.mkdir(parents=True)
        original_prefs = b'{"browser":{"theme":{"user_color2":123}}}\n'
        prefs.write_bytes(original_prefs)

        first = run([sys.executable, str(APPLY)], env)
        assert "Helium Gruvbox: dark" in first.stdout
        assert prefs.read_bytes() == original_prefs
        assert runtime_manifest(home).read_bytes() == DARK.read_bytes()

        rendered = flags.read_text()
        assert "--enable-features=SomethingUseful" in rendered
        assert "/tmp/user-extension" in rendered
        assert "--force-light-mode" not in rendered
        assert "install-autogenerated-theme" not in rendered
        assert "--remote-debugging-port=0" in rendered
        assert "dotfiles: helium gruvbox" in rendered
        runtime_dir = runtime_manifest(home).parent
        wrapper_safe = f"{home.parent}/./{home.name}{str(runtime_dir)[len(str(home)):]}"
        assert wrapper_safe in rendered

        # Applying twice is a no-op for both managed files.
        flags_before = flags.read_bytes()
        runtime_before = runtime_manifest(home).read_bytes()
        second = run([sys.executable, str(APPLY)], env)
        assert "Helium Gruvbox: dark (unchanged" in second.stdout
        assert flags.read_bytes() == flags_before
        assert runtime_manifest(home).read_bytes() == runtime_before
        assert prefs.read_bytes() == original_prefs

        # Direct mode switches exact source manifests even when Helium is closed.
        light = run(
            [sys.executable, str(SWITCH), "light", "--no-live-reload"],
            env,
        )
        assert "Helium Gruvbox: light (updated" in light.stdout
        assert runtime_manifest(home).read_bytes() == LIGHT.read_bytes()

        # auto follows darkman get.
        env = env_for(home, "dark")
        auto = run(
            [sys.executable, str(SWITCH), "auto", "--no-live-reload"],
            env,
        )
        assert "Helium Gruvbox: dark (updated" in auto.stdout
        assert runtime_manifest(home).read_bytes() == DARK.read_bytes()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
