#!/usr/bin/env python3
"""Configure Helium's built-in adaptive Chromium User Color theme."""

from __future__ import annotations

import argparse
import copy
import json
import os
import shutil
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parent.parent
PALETTE = ROOT / "colors.toml"
USER_COLOR_THEME_ID = "user_color_theme_id"
BROWSER_COLOR_SCHEMES = {"system": 0, "light": 1, "dark": 2}
COLOR_VARIANTS = {
    "system": 0,
    "tonal-spot": 1,
    "neutral": 2,
    "vibrant": 3,
    "expressive": 4,
}
MANAGED_BLOCKS = (
    ("# >>> dotfiles: helium gruvbox >>>", "# <<< dotfiles: helium gruvbox <<<"),
    (
        "# >>> dotfiles: helium web color-scheme >>>",
        "# <<< dotfiles: helium web color-scheme <<<",
    ),
)
OLD_THEME_MARKERS = (
    "helium-gruvbox-theme",
    "/helium/gruvbox-material",
    "/dotfiles/helium-gruvbox",
)
OLD_THEME_DIRS = (
    "helium-gruvbox",
    "helium-gruvbox-dark",
    "helium-gruvbox-light",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Configure Helium to use Chromium's native adaptive User Color theme. "
            "The browser then follows the system light/dark portal live."
        )
    )
    parser.add_argument(
        "--config-home",
        type=Path,
        help="override XDG_CONFIG_HOME (default: environment or ~/.config)",
    )
    parser.add_argument(
        "--data-home",
        type=Path,
        help="override XDG_DATA_HOME (default: environment or ~/.local/share)",
    )
    return parser.parse_args()


def load_helium_config() -> dict[str, str]:
    with PALETTE.open("rb") as handle:
        data = tomllib.load(handle)
    config = data.get("helium")
    if not isinstance(config, dict):
        raise ValueError(f"missing [helium] in {PALETTE}")

    user_color = config.get("user_color")
    if (
        not isinstance(user_color, str)
        or len(user_color) != 7
        or not user_color.startswith("#")
    ):
        raise ValueError(f"invalid helium.user_color in {PALETTE}: {user_color!r}")
    try:
        int(user_color[1:], 16)
    except ValueError as error:
        raise ValueError(
            f"invalid helium.user_color in {PALETTE}: {user_color!r}"
        ) from error

    color_variant = config.get("color_variant")
    if color_variant not in COLOR_VARIANTS:
        raise ValueError(
            f"invalid helium.color_variant in {PALETTE}: {color_variant!r}"
        )
    color_scheme = config.get("color_scheme")
    if color_scheme not in BROWSER_COLOR_SCHEMES:
        raise ValueError(
            f"invalid helium.color_scheme in {PALETTE}: {color_scheme!r}"
        )
    return {
        "user_color": user_color,
        "color_variant": str(color_variant),
        "color_scheme": str(color_scheme),
    }


def sk_color(value: str) -> int:
    """Convert #RRGGBB to Chromium's signed int representation of SkColor."""
    unsigned = 0xFF000000 | int(value.removeprefix("#"), 16)
    return unsigned - (1 << 32) if unsigned >= (1 << 31) else unsigned


def nested_dict(root: dict, *keys: str) -> dict:
    current = root
    for key in keys:
        value = current.get(key)
        if not isinstance(value, dict):
            value = {}
            current[key] = value
        current = value
    return current


def remove_key(root: dict, *keys: str) -> None:
    if not keys:
        return
    current = root
    for key in keys[:-1]:
        value = current.get(key)
        if not isinstance(value, dict):
            return
        current = value
    current.pop(keys[-1], None)


def desired_preferences(preferences: dict, config: dict[str, str]) -> dict:
    result = copy.deepcopy(preferences)
    browser_theme = nested_dict(result, "browser", "theme")
    extensions_theme = nested_dict(result, "extensions", "theme")

    color = sk_color(config["user_color"])
    variant = COLOR_VARIANTS[config["color_variant"]]
    scheme = BROWSER_COLOR_SCHEMES[config["color_scheme"]]

    # Chromium currently migrates these prefs to the *2 variants. Writing both
    # keeps Helium compatible across nearby Chromium revisions while the old
    # names still exist as migration inputs.
    browser_theme["color_scheme"] = scheme
    browser_theme["color_scheme2"] = scheme
    browser_theme["user_color"] = color
    browser_theme["user_color2"] = color
    browser_theme["color_variant"] = variant
    browser_theme["color_variant2"] = variant
    browser_theme["follows_system_colors"] = False
    browser_theme["is_grayscale"] = False
    browser_theme["is_grayscale2"] = False

    # This is Chromium's special built-in theme ID, not an installed extension.
    extensions_theme["id"] = USER_COLOR_THEME_ID
    for key in ("pack", "colors", "images", "tints", "properties"):
        extensions_theme.pop(key, None)

    # Remove the older autogenerated-theme seed so it cannot win on startup.
    remove_key(result, "autogenerated", "theme", "color")
    return result


def sandboxed() -> bool:
    real_home = os.environ.get("DOTS_REAL_HOME")
    return bool(real_home and Path(real_home).expanduser() != Path.home())


def helium_running() -> bool:
    """Detect a real Helium process without depending on pgrep."""
    proc = Path("/proc")
    if not proc.is_dir():
        return False
    for entry in proc.iterdir():
        if not entry.name.isdigit():
            continue
        try:
            argv = (entry / "cmdline").read_bytes().split(b"\0")
        except (OSError, PermissionError):
            continue
        if not argv or not argv[0]:
            continue
        first = argv[0].decode(errors="ignore")
        joined = b" ".join(argv).decode(errors="ignore")
        if "helium-browser" in first or "/opt/helium-browser" in joined:
            return True
    return False


def write_json_atomic(path: Path, data: dict) -> None:
    temp = path.with_name(path.name + ".dotfiles-tmp")
    temp.write_text(json.dumps(data, ensure_ascii=False, separators=(",", ":")))
    os.replace(temp, path)


def configure_profile(preferences_path: Path, config: dict[str, str]) -> str:
    if not preferences_path.exists():
        return "missing"
    try:
        current = json.loads(preferences_path.read_text())
    except json.JSONDecodeError as error:
        raise ValueError(f"invalid Helium Preferences JSON: {preferences_path}") from error
    if not isinstance(current, dict):
        raise ValueError(f"invalid Helium Preferences root: {preferences_path}")

    desired = desired_preferences(current, config)
    if desired == current:
        return "unchanged"
    if not sandboxed() and helium_running():
        raise RuntimeError(
            "Helium is running. Quit it once before the first adaptive-theme migration, "
            "then rerun `./dots apply`. Future light/dark switches do not need a restart."
        )
    write_json_atomic(preferences_path, desired)
    return "updated"


def strip_quotes(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
        return value[1:-1]
    return value


def clean_flags(flags_path: Path) -> bool:
    if not flags_path.exists() and not flags_path.is_symlink():
        return False
    if flags_path.is_symlink():
        target = os.readlink(flags_path)
        if "/helium/helium-browser-flags.conf" in target:
            flags_path.unlink()
            return True
        raise RuntimeError(
            f"refusing to replace user-managed symlink {flags_path} -> {target}"
        )

    original = flags_path.read_text()
    backup = flags_path.with_suffix(flags_path.suffix + ".gruvbox-backup")
    if original and not backup.exists() and not sandboxed():
        shutil.copy2(flags_path, backup)

    starts = {start: end for start, end in MANAGED_BLOCKS}
    ends = {end for _, end in MANAGED_BLOCKS}
    output: list[str] = []
    active_end: str | None = None

    for line in original.splitlines():
        stripped = line.strip()
        if active_end is not None:
            if stripped == active_end:
                active_end = None
            continue
        if stripped in starts:
            active_end = starts[stripped]
            continue
        if stripped in ends:
            continue

        if stripped.startswith("--load-extension="):
            raw = strip_quotes(stripped.split("=", 1)[1])
            kept = []
            for entry in raw.split(","):
                candidate = strip_quotes(entry.strip())
                if candidate and not any(marker in candidate for marker in OLD_THEME_MARKERS):
                    kept.append(candidate)
            if kept:
                output.append("--load-extension=" + ",".join(kept))
            continue
        output.append(line)

    while output and not output[-1].strip():
        output.pop()
    rendered = "\n".join(output)
    if rendered:
        rendered += "\n"

    if rendered == original:
        return False
    if rendered:
        flags_path.write_text(rendered)
    else:
        flags_path.unlink()
    return True


def clean_old_runtime(data_home: Path) -> list[Path]:
    removed: list[Path] = []
    root = data_home / "dotfiles"
    for name in OLD_THEME_DIRS:
        path = root / name
        if path.is_dir() and not path.is_symlink():
            shutil.rmtree(path)
            removed.append(path)
        elif path.exists() or path.is_symlink():
            path.unlink()
            removed.append(path)
    return removed


def main() -> int:
    args = parse_args()
    config_home = (
        args.config_home.expanduser()
        if args.config_home
        else Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    )
    data_home = (
        args.data_home.expanduser()
        if args.data_home
        else Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local/share"))
    )
    preferences = config_home / "helium" / "Default" / "Preferences"
    flags = config_home / "helium-browser-flags.conf"

    try:
        config = load_helium_config()
        status = configure_profile(preferences, config)
        flags_changed = clean_flags(flags)
        removed = clean_old_runtime(data_home)
    except (OSError, ValueError, RuntimeError) as error:
        print(f"helium-adaptive-theme: {error}")
        return 1

    print("Helium theme: Chromium User Color (adaptive)")
    print(f"Helium seed: {config['user_color']} ({config['color_variant']})")
    print(f"Helium color scheme: {config['color_scheme']}")
    if status == "missing":
        print(
            f"Helium Preferences not found: {preferences}\n"
            "Launch Helium once, close it, then rerun `./dots apply`."
        )
    elif status == "updated":
        print(f"Configured: {preferences}")
        print("Start Helium once. After that, darkman light/dark changes are live.")
    else:
        print(f"Already configured: {preferences}")
    if flags_changed:
        print(f"Removed legacy Gruvbox extension flags: {flags}")
    for path in removed:
        print(f"Removed legacy Gruvbox runtime: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
