// Generated by scripts/generate-theme.py from colors.toml. Do not edit.
import QtQuick

QtObject {
  readonly property color bgHard: "#1d2021"
  readonly property color bg: "#282828"
  readonly property color bgAlt: "#32302f"
  readonly property color bgSoft: "#3c3836"
  readonly property color bgHover: "#504945"
  readonly property color bgMuted: "#665c54"
  readonly property color fg: "#d4be98"
  readonly property color fgUi: "#ebdbb2"
  readonly property color fgBright: "#fbf1c7"
  readonly property color fgSoft: "#d5c4a1"
  readonly property color gray: "#928374"
  readonly property color grayDim: "#a89984"
  readonly property color red: "#ea6962"
  readonly property color green: "#a9b665"
  readonly property color yellow: "#d8a657"
  readonly property color orange: "#e78a4e"
  readonly property color blue: "#7daea3"
  readonly property color purple: "#d3869b"
  readonly property color aqua: "#89b482"
  readonly property color bgHard95: "#f51d2021"
}
