#!/usr/bin/env python3
"""Generate tracked Gruvbox theme surfaces from colors.toml."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[1]
PALETTE = ROOT / "colors.toml"


def load_colors() -> dict[str, str]:
    data = tomllib.loads(PALETTE.read_text())
    colors = data["colors"]
    for name, value in colors.items():
        if not isinstance(value, str) or len(value) != 7 or not value.startswith("#"):
            raise ValueError(f"colors.toml: invalid {name}={value!r}")
    return colors


def rgb(value: str) -> str:
    return value.removeprefix("#")


def render_kitty(c: dict[str, str]) -> str:
    return f"""# vim:ft=kitty
# Generated by scripts/generate-theme.py from colors.toml. Do not edit colors here.
## name: Gruvbox Material Dark Medium
## author: Sainnhe Park
## license: MIT
## upstream: https://raw.githubusercontent.com/rsaihe/gruvbox-material-kitty/main/colors/gruvbox-material-dark-medium.conf
## blurb: Medium-contrast Gruvbox Material; background {c['bg']} matches nvim.

background {c['bg']}
foreground {c['fg']}

selection_background {c['fg']}
selection_foreground {c['bg']}

cursor {c['gray_dim']}
cursor_text_color background

# Black
color0 {c['bg_muted']}
color8 {c['gray']}

# Red
color1 {c['red']}
color9 {c['red']}

# Green
color2  {c['green']}
color10 {c['green']}

# Yellow
color3  {c['orange']}
color11 {c['yellow']}

# Blue
color4  {c['blue']}
color12 {c['blue']}

# Magenta
color5  {c['purple']}
color13 {c['purple']}

# Cyan
color6  {c['aqua']}
color14 {c['aqua']}

# White
color7  {c['fg']}
color15 {c['fg']}

# Gruvbox Material tab bar
active_tab_foreground   {c['bg']}
active_tab_background   {c['yellow']}
inactive_tab_foreground {c['gray_dim']}
inactive_tab_background {c['bg_soft']}
tab_bar_background      {c['bg']}
tab_bar_margin_color    {c['bg']}
"""


def render_qat(c: dict[str, str]) -> str:
    terminal = [
        c["bg_muted"], c["red"], c["green"], c["orange"], c["blue"], c["purple"], c["aqua"], c["fg"],
        c["gray"], c["red"], c["green"], c["yellow"], c["blue"], c["purple"], c["aqua"], c["fg"],
    ]
    lines = [
        "# Generated by scripts/generate-theme.py from colors.toml.",
        "edge center-sized",
        f"kitty_override background={c['bg']}",
        f"kitty_override foreground={c['fg']}",
        f"kitty_override selection_background={c['fg']}",
        f"kitty_override selection_foreground={c['bg']}",
        f"kitty_override cursor={c['gray_dim']}",
        "kitty_override cursor_text_color=background",
    ]
    lines.extend(f"kitty_override color{i}={value}" for i, value in enumerate(terminal))
    lines.extend([
        "kitty_override tab_bar_style=hidden",
        "lines 22",
        "columns 90",
        "background_opacity 0.85",
        "",
    ])
    return "\n".join(lines)


def render_waybar(c: dict[str, str]) -> str:
    names = [
        ("gb_bg", "bg"), ("gb_bg_alt", "bg_alt"), ("gb_bg_soft", "bg_soft"),
        ("gb_fg", "fg"), ("gb_gray", "gray"), ("gb_gray_dim", "gray_dim"),
        ("gb_red", "red"), ("gb_green", "green"), ("gb_yellow", "yellow"),
        ("gb_orange", "orange"), ("gb_blue", "blue"), ("gb_purple", "purple"),
        ("gb_aqua", "aqua"),
    ]
    out = ["/* Generated by scripts/generate-theme.py from colors.toml. */"]
    out.extend(f"@define-color {css} {c[key]};" for css, key in names)
    return "\n".join(out) + "\n"


def render_shell_colors(c: dict[str, str]) -> str:
    qml_names = {
        "bgHard": "bg_hard", "bg": "bg", "bgAlt": "bg_alt", "bgSoft": "bg_soft",
        "bgHover": "bg_hover", "bgMuted": "bg_muted", "fg": "fg", "fgUi": "fg_ui",
        "fgBright": "fg_bright", "fgSoft": "fg_soft", "gray": "gray", "grayDim": "gray_dim",
        "red": "red", "green": "green", "yellow": "yellow", "orange": "orange",
        "blue": "blue", "purple": "purple", "aqua": "aqua",
    }
    lines = [
        "// Generated by scripts/generate-theme.py from colors.toml. Do not edit.",
        "import QtQuick",
        "",
        "QtObject {",
    ]
    lines.extend(f'  readonly property color {name}: "{c[key]}"' for name, key in qml_names.items())
    lines.append(f'  readonly property color bgHard95: "#f5{rgb(c["bg_hard"])}"')
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_hypr(c: dict[str, str]) -> str:
    return f"""# Generated by scripts/generate-theme.py from colors.toml.
$lock_inner = rgba({rgb(c['bg'])}cc)
$lock_outer_start = rgba({rgb(c['yellow'])}ee)
$lock_outer_end = rgba({rgb(c['green'])}ee)
$lock_check_start = rgba({rgb(c['aqua'])}ee)
$lock_check_end = rgba({rgb(c['yellow'])}ee)
$lock_fail_start = rgba({rgb(c['red'])}ee)
$lock_fail_end = rgba({rgb(c['orange'])}ee)
$lock_fg = rgba({rgb(c['fg'])}ff)
$lock_fg_dim = rgba({rgb(c['gray_dim'])}ff)
$lock_accent = rgba({rgb(c['yellow'])}ff)
"""


def render_shell(c: dict[str, str]) -> str:
    exported = ["bg", "bg_alt", "bg_soft", "fg", "gray", "gray_dim", "red", "green", "yellow", "orange", "blue", "purple", "aqua"]
    lines = ["# Generated by scripts/generate-theme.py from colors.toml."]
    lines.extend(f"GB_{name.upper()}='{c[name]}'" for name in exported)
    return "\n".join(lines) + "\n"


def render_claude(c: dict[str, str]) -> str:
    overrides = {
        "claude": c["yellow"], "text": c["fg"], "inverseText": c["bg_hard"], "inactive": c["gray"],
        "subtle": c["bg_hover"], "suggestion": c["blue"], "permission": c["purple"],
        "remember": c["orange"], "success": c["green"], "error": c["red"], "warning": c["yellow"],
        "merged": c["aqua"], "promptBorder": c["bg_muted"], "planMode": c["aqua"],
        "autoAccept": c["green"], "bashBorder": c["blue"], "ide": c["blue"], "fastMode": c["orange"],
        "diffAdded": c["diff_added"], "diffRemoved": c["diff_removed"],
        "diffAddedDimmed": c["diff_added_dimmed"], "diffRemovedDimmed": c["diff_removed_dimmed"],
        "diffAddedWord": c["green"], "diffRemovedWord": c["red"], "userMessageBackground": c["bg_alt"],
        "userMessageBackgroundHover": c["bg_soft"], "bashMessageBackgroundColor": c["bg_alt"],
        "memoryBackgroundColor": c["bg_alt"], "selectionBg": c["yellow"], "rate_limit_fill": c["green"],
        "rate_limit_empty": c["bg_hover"], "briefLabelYou": c["fg"], "briefLabelClaude": c["yellow"],
        "red_FOR_SUBAGENTS_ONLY": c["red"], "blue_FOR_SUBAGENTS_ONLY": c["blue"],
        "green_FOR_SUBAGENTS_ONLY": c["green"], "yellow_FOR_SUBAGENTS_ONLY": c["yellow"],
        "purple_FOR_SUBAGENTS_ONLY": c["purple"], "orange_FOR_SUBAGENTS_ONLY": c["orange"],
        "pink_FOR_SUBAGENTS_ONLY": c["purple"], "cyan_FOR_SUBAGENTS_ONLY": c["aqua"],
        "rainbow_red": c["red"], "rainbow_red_shimmer": c["purple"], "rainbow_orange": c["orange"],
        "rainbow_orange_shimmer": c["yellow"], "rainbow_yellow": c["yellow"],
        "rainbow_yellow_shimmer": c["orange"], "rainbow_green": c["green"],
        "rainbow_green_shimmer": c["aqua"], "rainbow_blue": c["blue"],
        "rainbow_blue_shimmer": c["aqua"], "rainbow_indigo": c["purple"],
        "rainbow_indigo_shimmer": c["blue"], "rainbow_violet": c["purple"],
        "rainbow_violet_shimmer": c["orange"],
    }
    return json.dumps({"name": "gruvbox-material", "base": "dark", "overrides": overrides}, indent=2) + "\n"


def render_yazi(c: dict[str, str]) -> str:
    # Keep the current classic-Gruvbox Yazi flavor byte-for-byte in structure;
    # only its color values come from the shared palette.
    return f'''# vim:fileencoding=utf-8:foldmethod=marker
# Generated by scripts/generate-theme.py from colors.toml. Do not edit colors here.

[mgr]
cwd = {{ fg = "{c['legacy_blue']}" }}
find_keyword  = {{ fg = "{c['legacy_green']}", bold = true, italic = true, underline = true }}
find_position = {{ fg = "{c['legacy_orange']}", bg = "reset", bold = true, italic = true }}
symlink_target = {{ italic = true }}
marker_copied   = {{ fg = "{c['legacy_aqua']}", bg = "{c['legacy_aqua']}" }}
marker_cut      = {{ fg = "{c['purple']}", bg = "{c['purple']}" }}
marker_marked   = {{ fg = "{c['legacy_blue']}", bg = "{c['legacy_blue']}" }}
marker_selected = {{ fg = "{c['fg_bright']}", bg = "{c['fg_bright']}" }}
count_copied   = {{ fg = "{c['bg']}", bg = "{c['legacy_aqua']}" }}
count_cut      = {{ fg = "{c['bg']}", bg = "{c['purple']}" }}
count_selected = {{ fg = "{c['bg']}", bg = "{c['fg_bright']}" }}
border_symbol = "│"
border_style  = {{ fg = "{c['bg_muted']}" }}

[tabs]
active   = {{ fg = "{c['bg']}", bg = "{c['gray_dim']}" }}
inactive = {{ fg = "{c['gray_dim']}", bg = "{c['bg_hover']}" }}
sep_inner = {{ open = "", close = "" }}
sep_outer = {{ open = "", close = "" }}

[mode]
normal_main = {{ fg = "{c['bg']}", bg = "{c['gray_dim']}", bold = true }}
normal_alt  = {{ fg = "{c['gray_dim']}", bg = "{c['bg_hover']}" }}
select_main = {{ fg = "{c['bg']}", bg = "{c['legacy_orange']}", bold = true }}
select_alt  = {{ fg = "{c['gray_dim']}", bg = "{c['bg_hover']}" }}
unset_main = {{ fg = "{c['bg']}", bg = "{c['legacy_green']}", bold = true }}
unset_alt  = {{ fg = "{c['gray_dim']}", bg = "{c['bg_hover']}" }}

[indicator]
parent  = {{ reversed = true }}
current = {{ reversed = true }}
preview = {{ underline = true }}
padding = {{ open = "█", close = "█" }}

[status]
overall = {{ }}
sep_left = {{ open = "\\ue0be", close = "\\ue0b8" }}
sep_right = {{ open = "\\ue0be", close = "\\ue0b8" }}
perm_sep   = {{ fg = "{c['bg_muted']}" }}
perm_type  = {{ fg = "{c['bg_hover']}" }}
perm_read  = {{ fg = "{c['legacy_green']}" }}
perm_write = {{ fg = "{c['legacy_red']}" }}
perm_exec  = {{ fg = "{c['legacy_green']}" }}
progress_label  = {{ fg = "{c['fg_ui']}", bold = true }}
progress_normal = {{ fg = "{c['bg_hover']}", bg = "{c['bg_soft']}" }}
progress_error  = {{ fg = "{c['legacy_red']}", bg = "{c['bg_soft']}" }}

[which]
cols            = 3
mask            = {{ bg = "{c['bg_soft']}" }}
cand            = {{ fg = "{c['legacy_blue']}" }}
rest            = {{ fg = "{c['gray']}" }}
desc            = {{ fg = "{c['legacy_orange']}" }}
separator       = "  "
separator_style = {{ fg = "{c['bg_hover']}" }}

[confirm]
border     = {{ fg = "{c['gray_dim']}" }}
title      = {{ fg = "{c['legacy_blue']}" }}
body       = {{ fg = "{c['fg_bright']}" }}
list       = {{ fg = "{c['fg_ui']}" }}
btn_yes    = {{ reversed = true, fg = "{c['fg_ui']}" }}
btn_no     = {{}}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[spot]
border = {{ fg = "{c['legacy_blue']}" }}
title  = {{ fg = "{c['legacy_blue']}" }}
tbl_col  = {{ fg = "{c['legacy_blue']}" }}
tbl_cell = {{ fg = "{c['legacy_yellow']}", reversed = true }}

[notify]
title_info  = {{ fg = "{c['legacy_aqua']}" }}
title_warn  = {{ fg = "{c['fg_bright']}" }}
title_error = {{ fg = "{c['purple']}" }}

[pick]
border   = {{ fg = "{c['legacy_blue_dark']}" }}
active   = {{ fg = "{c['purple']}", bold = true }}
inactive = {{}}

[input]
border   = {{ fg = "{c['fg_ui']}" }}
title    = {{}}
value    = {{}}
selected = {{ reversed = true }}

[cmp]
border   = {{ fg = "{c['gray_dim']}" }}
active   = {{ reversed = true, fg = "{c['legacy_blue']}" }}
inactive = {{ fg = "{c['fg_ui']}" }}

[tasks]
border  = {{ fg = "{c['bg_hover']}" }}
title   = {{}}
hovered = {{ underline = true }}

[help]
on      = {{ fg = "{c['legacy_blue']}" }}
run     = {{ fg = "{c['purple']}" }}
desc    = {{}}
hovered = {{ reversed = true, bold = true }}
footer  = {{ fg = "{c['bg_soft']}", bg = "{c['gray_dim']}" }}

[filetype]
rules = [
  {{ mime = "image/*", fg = "{c['purple']}" }},
  {{ mime = "{{audio,video}}/*", fg = "{c['legacy_yellow']}" }},
  {{ mime = "application/*zip", fg = "{c['legacy_red']}" }},
  {{ mime = "application/x-{{tar,bzip*,7z-compressed,xz,rar}}", fg = "{c['legacy_red']}" }},
  {{ mime = "application/{{pdf,doc,rtf,vnd.*}}", fg = "{c['legacy_green_dark']}" }},
  {{ url = "*", fg = "{c['fg_ui']}" }},
  {{ url = "*/", fg = "{c['legacy_blue']}" }},
]
'''


def generated_files(c: dict[str, str]) -> dict[Path, str]:
    return {
        ROOT / "kitty/current-theme.conf": render_kitty(c),
        ROOT / "kitty/quick-access-terminal-center.conf": render_qat(c),
        ROOT / "waybar/colors.css": render_waybar(c),
        ROOT / "hypr/colors.conf": render_hypr(c),
        ROOT / "scripts/generated-colors.sh": render_shell(c),
        ROOT / "quickshell/config/Colors.qml": render_shell_colors(c),
        ROOT / ".claude/themes/gruvbox-material.json": render_claude(c),
        ROOT / "yazi/flavors/gruvbox-dark.yazi/flavor.toml": render_yazi(c),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    files = generated_files(load_colors())
    stale: list[str] = []
    for path, content in files.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    if stale:
        print("stale generated theme files:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())