-- return {
--   "nestermaks/hypr-xkb",
--   event = { "VeryLazy" },
--   opts = {
--     device = "kanata",
--     normal_layout = "us",
--     check = true,
--     lang_codes = { "us", "ru" },
--     layout_ids = {
--       ["English (US)"] = 0,
--       ["Russian"] = 1,
--       normal = 0,
--     },
--   },
-- }
