unbind r
bind r source-file ~/.tmux.conf
unbind d
bind d switch-client -t todo

tmux_sessionizer="~/dotfiles/tmux/tools/prime/tmux-sessionizer.sh"
unbind C-t
bind-key -r C-t run-shell "$tmux_sessionizer ~/obsidiansync"
unbind C-d
bind-key -r C-d run-shell "$tmux_sessionizer ~/obsidiansync/base/notes/todo.md"
unbind C-c
bind-key -r C-c run-shell "$tmux_sessionizer ~/code/cpp"
bind-key -r C-q run-shell "$tmux_sessionizer ~/obsidiansync/base/notes/Day_1.md"
bind-key -r C-w run-shell "$tmux_sessionizer ~/obsidiansync/base/notes/Day_2.md"
bind-key -r C-e run-shell "$tmux_sessionizer ~/obsidiansync/base/notes/Day_3.md"


bind-key x kill-pane
unbind Space
bind-key Space switch-client -l


set -g prefix C-s

set -g mouse on

set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set date in US notation



# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g status-right ""
set -g status-right "#[fg=brightblack]#{pane_current_path} #[default]"
