# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-vi-mode
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run alias.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

### aichat ###
_aichat_zsh() {
    if [[ -n "$BUFFER" ]]; then
        local _old=$BUFFER
        BUFFER+=" ⏳"
        zle -I && zle redisplay
        BUFFER=$(command aichat -r '%shell%' "$_old")
        zle end-of-line
    fi
}
zle -N _aichat_zsh
bindkey '\ee' _aichat_zsh
alias ai="aichat"


# Конфигурация im-select: укажите команду и идентификаторы раскладок
IM_SELECT_CMD="/mnt/c/windows/im-select.exe"
IM_EN="1033"  
IM_RU="1049"

set_im() { command "$IM_SELECT_CMD" "$1" >/dev/null 2>&1; }
get_im() { command "$IM_SELECT_CMD" 2>/dev/null; }

typeset -g IM_LAST=""

zle-im-keymap-select() {
  # Не трогаем keymap здесь, только переключаем раскладку
  if [[ $KEYMAP == vicmd ]]; then
    [[ -z $IM_LAST ]] && IM_LAST=$(get_im)
    [[ -n $IM_EN ]] && set_im "$IM_EN"
  else
    [[ -n $IM_LAST ]] && set_im "$IM_LAST"
  fi
}
zle -N zle-im-keymap-select

# Автопереключение при смене keymap и на старте строки
zle -N zle-keymap-select zle-im-keymap-select
zle-line-init() { zle-im-keymap-select; }
zle -N zle-line-init

# Vim
export vi=~/.config/nvim/init.lua
bindkey -v
bindkey -M vicmd 'H' vi-first-non-blank
bindkey -M vicmd 'L' end-of-line
alias vif="nvim ~/.config/nvim"
alias vip="nvim ~/.config/nvim/lua/plugins"
alias vi="nvim"
alias sync-vi="cp -r ~/.config/nvim/ ~/dotfiles/.config/"
alias sv="cp -r ~/.config/nvim/ ~/dotfiles/.config/"

export PATH=~/.npm-global/bin:$PATH
export PATH="$HOME/.local/bin:$PATH"
#export win_username="$(powershell.exe -c 'echo $env:USERNAME' | tr -d '\r')"
#export winuser="/mnt/c/Users/$win_username"
export OPENROUTER_API_KEY="sk-rGiKULn5W3H6Yf8TbzWi4Iu1wnFUTf7y"
export PATH="$HOME/.local/bin:$PATH"
export BROWSER=zen-browser
export TERMCMD="wezterm"

export zsh=~/.zshrc
export glaze="$winuser/.glzr/glazewm/config.yaml"
export dots=~/dotfiles
export df=~/dotfiles
export downloads="/home/shafed/Downloads"
export ds="/home/shafed/Downloads"

alias shell:startup="cd \"$winuser/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup\""
alias open="explorer.exe"
alias sync-alacritty="~/.local/bin/sync-alacritty"
alias sa="~/.local/bin/sync-alacritty"
alias edit-alacritty="nvim ~/.config/alacritty/alacritty.toml"
alias ea="nvim ~/.config/alacritty/alacritty.toml"
alias sync-glaze="cp $winuser/.glzr/glazewm/config.yaml ~/dotfiles/windows/"
alias sgl="cp $winuser/.glzr/glazewm/config.yaml ~/dotfiles/windows/"
alias sync-zsh="cp ~/.zshrc ~/dotfiles/.config/zsh/"
alias sz="cp ~/.zshrc ~/dotfiles/zsh/"
alias sync-all="\
  cp ~/dotfiles/windows/config.yaml $winuser/.glzr/glazewm/config.yaml && \
  cp ~/dotfiles/.config/zsh/.zshrc ~/.zshrc && \
  cp -r ~/dotfiles/.config/nvim/ ~/.config/"


# Yazi cd
alias y="yazi"
export EDITOR=nvim
export VISUAL=nvim
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

alias neobean='NVIM_APPNAME=linkarzu/dotfiles-latest/neovim/neobean nvim'
alias nb='neobean'

alias ta="task add"
alias tl="task list"

# Zoxide
eval "$(zoxide init zsh)"
alias cd="z"
alias cdd="z -"
alias pulldeez='echo "Pulling latest changes, please wait..."; (cd ~/dotfiles && git pull >/dev/null 2>&1) || echo "Failed to pull dotfiles"; source ~/.zshrc'
alias sioyek="LIBGL_ALWAYS_SOFTWARE=1 sioyek"

export TODOIST_API_TOKEN="f3736efb85c6f5c726090bb92df83fa9b07a6b19"

# OpenClaw Completion
source "/home/shafed/.openclaw/completions/openclaw.zsh"
