#Чтобы отключить обрезание экрана у nvim, нужно зайти через Проводник в Свойства -> Совместимость и нажать галочку "Отключить оптимизацию во весь экран"

# --- Среда ---
[env]
TERM = "xterm-256color"

# --- Оболочка: сразу в Debian + zsh как login-shell ---
[terminal.shell]
program = "wsl.exe"
args = ["-d", "Debian", "--cd", "~", "-e", "zsh", "-l"]
# --- Шрифт ---
[font]
size = 12

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

# --- Прокрутка ---
[scrolling]
history = 20000   # сделай 5000–20000; 0 = без лимита (медленнее)

# --- Цвета ---
[colors.primary]
background = '#282828'
foreground = '#dfbf8e'

[colors.normal]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e78a4e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e3a84e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'


