#!/usr/bin/env python3
"""Generate the Telegram Desktop Gruvbox theme from the shared palette."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[1]
PALETTE = ROOT / "colors.toml"
OUTPUT = Path(__file__).with_name("gruvbox-material-dark-medium.tdesktop-theme")


def load_colors() -> dict[str, str]:
    data = tomllib.loads(PALETTE.read_text())
    colors = data["colors"]
    for name, value in colors.items():
        if not isinstance(value, str) or len(value) != 7 or not value.startswith("#"):
            raise ValueError(f"colors.toml: invalid {name}={value!r}")
    return colors


def render(c: dict[str, str]) -> str:
    return f"""// Generated by telegram/generate-theme.py from colors.toml. Do not edit colors here.
// Gruvbox Material Dark Medium for Telegram Desktop.

GB_BG_HARD: {c['bg_hard']};
GB_BG: {c['bg']};
GB_BG_ALT: {c['bg_alt']};
GB_BG_SOFT: {c['bg_soft']};
GB_BG_HOVER: {c['bg_hover']};
GB_BG_MUTED: {c['bg_muted']};
GB_FG: {c['fg']};
GB_FG_UI: {c['fg_ui']};
GB_FG_BRIGHT: {c['fg_bright']};
GB_FG_SOFT: {c['fg_soft']};
GB_GRAY: {c['gray']};
GB_GRAY_DIM: {c['gray_dim']};
GB_RED: {c['red']};
GB_GREEN: {c['green']};
GB_YELLOW: {c['yellow']};
GB_ORANGE: {c['orange']};
GB_BLUE: {c['blue']};
GB_PURPLE: {c['purple']};
GB_AQUA: {c['aqua']};

// Window and controls.
windowBg: GB_BG;
windowFg: GB_FG;
windowBgOver: GB_BG_ALT;
windowBgRipple: GB_BG_HOVER;
windowFgOver: GB_FG_BRIGHT;
windowSubTextFg: GB_GRAY_DIM;
windowSubTextFgOver: GB_FG_SOFT;
windowBoldFg: GB_FG_UI;
windowBoldFgOver: GB_FG_BRIGHT;
windowBgActive: GB_YELLOW;
windowFgActive: GB_BG_HARD;
windowActiveTextFg: GB_YELLOW;
windowShadowFg: #00000066;
windowShadowFgFallback: GB_BG_HARD;
shadowFg: #00000040;
slideFadeOutBg: #00000066;
imageBg: GB_BG_HARD;
imageBgTransparent: GB_BG;

activeButtonBg: GB_YELLOW;
activeButtonBgOver: GB_ORANGE;
activeButtonBgRipple: GB_BG_MUTED;
activeButtonFg: GB_BG_HARD;
activeButtonFgOver: GB_BG_HARD;
activeButtonSecondaryFg: GB_BG;

attentionButtonFg: GB_RED;
attentionButtonFgOver: GB_ORANGE;
attentionButtonBgOver: GB_BG_ALT;
attentionButtonBgRipple: GB_BG_HOVER;

outlineButtonBg: GB_BG;
outlineButtonBgOver: GB_BG_ALT;
outlineButtonOutlineFg: GB_BG_MUTED;
outlineButtonOutlineFgOver: GB_YELLOW;
outlineButtonFg: GB_FG;
outlineButtonFgOver: GB_FG_BRIGHT;

inputBorderFg: GB_BG_MUTED;
inputBorderFgActive: GB_YELLOW;
inputBg: GB_BG_ALT;
inputBgActive: GB_BG_ALT;
inputFg: GB_FG;
inputPlaceholderFg: GB_GRAY;
inputPlaceholderFgActive: GB_GRAY_DIM;

// Lists, chats and unread state.
dialogsBg: GB_BG;
dialogsBgOver: GB_BG_ALT;
dialogsBgActive: GB_BG_HOVER;
dialogsNameFg: GB_FG_UI;
dialogsNameFgOver: GB_FG_BRIGHT;
dialogsNameFgActive: GB_FG_BRIGHT;
dialogsTextFg: GB_GRAY_DIM;
dialogsTextFgOver: GB_FG_SOFT;
dialogsTextFgActive: GB_FG;
dialogsTextFgService: GB_BLUE;
dialogsTextFgServiceOver: GB_BLUE;
dialogsTextFgServiceActive: GB_AQUA;
dialogsDateFg: GB_GRAY;
dialogsDateFgOver: GB_GRAY_DIM;
dialogsDateFgActive: GB_FG_SOFT;
dialogsUnreadBg: GB_YELLOW;
dialogsUnreadBgOver: GB_ORANGE;
dialogsUnreadBgActive: GB_YELLOW;
dialogsUnreadFg: GB_BG_HARD;
dialogsUnreadFgOver: GB_BG_HARD;
dialogsUnreadFgActive: GB_BG_HARD;
dialogsVerifiedIconBg: GB_BLUE;
dialogsVerifiedIconFg: GB_BG_HARD;
dialogsDraftFg: GB_RED;
dialogsDraftFgOver: GB_RED;
dialogsDraftFgActive: GB_ORANGE;
dialogsSendingIconFg: GB_GRAY;
dialogsSendingIconFgOver: GB_GRAY_DIM;
dialogsSendingIconFgActive: GB_FG_SOFT;
dialogsSentIconFg: GB_GREEN;
dialogsSentIconFgOver: GB_GREEN;
dialogsSentIconFgActive: GB_GREEN;

// Search and menus.
menuBg: GB_BG_ALT;
menuBgOver: GB_BG_HOVER;
menuBgRipple: GB_BG_MUTED;
menuIconFg: GB_GRAY_DIM;
menuIconFgOver: GB_FG_UI;
menuFg: GB_FG;
menuFgDisabled: GB_GRAY;
menuSeparatorFg: GB_BG_MUTED;

emojiPanBg: GB_BG_ALT;
emojiPanCategories: GB_BG;
emojiPanHeaderBg: GB_BG;
emojiPanHeaderFg: GB_GRAY_DIM;
emojiPanHeaderFgOver: GB_FG_UI;
emojiPanHeaderFgActive: GB_YELLOW;
emojiPanSearchBg: GB_BG;
emojiPanSearchFg: GB_FG;
emojiPanSearchPlaceholderFg: GB_GRAY;
emojiPanSearchIconFg: GB_GRAY_DIM;

// Chat history and message bubbles.
historyTextInFg: GB_FG;
historyTextInFgSelected: GB_FG_BRIGHT;
historyTextOutFg: GB_FG;
historyTextOutFgSelected: GB_FG_BRIGHT;
historyLinkInFg: GB_BLUE;
historyLinkInFgSelected: GB_AQUA;
historyLinkOutFg: GB_AQUA;
historyLinkOutFgSelected: GB_BLUE;
historyFileNameInFg: GB_BLUE;
historyFileNameInFgSelected: GB_AQUA;
historyFileNameOutFg: GB_AQUA;
historyFileNameOutFgSelected: GB_BLUE;

msgInBg: GB_BG_ALT;
msgInBgSelected: GB_BG_HOVER;
msgOutBg: GB_BG_SOFT;
msgOutBgSelected: GB_BG_MUTED;
msgSelectOverlay: #d8a6574c;
msgStickerOverlay: #d8a65740;
msgInShadow: #00000020;
msgInShadowSelected: #00000030;
msgOutShadow: #00000020;
msgOutShadowSelected: #00000030;
msgInDateFg: GB_GRAY_DIM;
msgInDateFgSelected: GB_FG_SOFT;
msgOutDateFg: GB_GRAY_DIM;
msgOutDateFgSelected: GB_FG_SOFT;
msgServiceFg: GB_FG_SOFT;
msgServiceBg: #1d2021cc;
msgServiceBgSelected: #504945dd;
msgInServiceFg: GB_BLUE;
msgInServiceFgSelected: GB_AQUA;
msgOutServiceFg: GB_AQUA;
msgOutServiceFgSelected: GB_BLUE;
msgInReplyBarColor: GB_BLUE;
msgInReplyBarSelColor: GB_AQUA;
msgOutReplyBarColor: GB_AQUA;
msgOutReplyBarSelColor: GB_BLUE;
msgImgReplyBarColor: GB_YELLOW;
msgInMonoFg: GB_ORANGE;
msgOutMonoFg: GB_ORANGE;

historyComposeAreaBg: GB_BG;
historyComposeAreaFg: GB_FG;
historyComposeAreaFgService: GB_GRAY_DIM;
historyComposeIconFg: GB_GRAY_DIM;
historyComposeIconFgOver: GB_FG_UI;
historySendIconFg: GB_YELLOW;
historySendIconFgOver: GB_ORANGE;
historyPinnedBg: GB_BG;
historyReplyBg: GB_BG;
historyReplyCancelFg: GB_GRAY;
historyReplyCancelFgOver: GB_RED;
historyComposeButtonBg: GB_BG;
historyComposeButtonBgOver: GB_BG_ALT;
historyComposeButtonBgRipple: GB_BG_HOVER;

historyScrollBarBg: #a8998466;
historyScrollBarBgOver: #d4be9899;
historyScrollBg: #1d202100;
historyScrollBgOver: #50494555;
historyUnreadBarBg: GB_BG_ALT;
historyUnreadBarBorder: GB_BG_MUTED;
historyUnreadBarFg: GB_YELLOW;
historyForwardChooseBg: #1d2021aa;
historyForwardChooseFg: GB_FG_BRIGHT;
historySystemBg: #1d2021cc;
historySystemBgSelected: #504945dd;
historySystemFg: GB_FG_SOFT;

// Peer accents and avatars.
historyPeer1NameFg: GB_RED;
historyPeer1UserpicBg: GB_RED;
historyPeer2NameFg: GB_GREEN;
historyPeer2UserpicBg: GB_GREEN;
historyPeer3NameFg: GB_YELLOW;
historyPeer3UserpicBg: GB_YELLOW;
historyPeer4NameFg: GB_BLUE;
historyPeer4UserpicBg: GB_BLUE;
historyPeer5NameFg: GB_PURPLE;
historyPeer5UserpicBg: GB_PURPLE;
historyPeer6NameFg: GB_ORANGE;
historyPeer6UserpicBg: GB_ORANGE;
historyPeer7NameFg: GB_AQUA;
historyPeer7UserpicBg: GB_AQUA;
historyPeer8NameFg: GB_FG_SOFT;
historyPeer8UserpicBg: GB_BG_MUTED;
historyPeerUserpicFg: GB_BG_HARD;

// Media, files and playback.
mediaInFg: GB_GRAY_DIM;
mediaInFgSelected: GB_FG_SOFT;
mediaOutFg: GB_GRAY_DIM;
mediaOutFgSelected: GB_FG_SOFT;
mediaPlayerBg: GB_BG_ALT;
mediaPlayerActiveFg: GB_YELLOW;
mediaPlayerInactiveFg: GB_GRAY_DIM;
mediaPlayerDisabledFg: GB_GRAY;
mediaviewBg: #1d2021f2;
mediaviewMenuBg: GB_BG_ALT;
mediaviewMenuBgOver: GB_BG_HOVER;
mediaviewMenuBgRipple: GB_BG_MUTED;
mediaviewMenuFg: GB_FG_UI;
mediaviewFileBg: GB_BG_ALT;
mediaviewFileNameFg: GB_FG_UI;
mediaviewFileSizeFg: GB_GRAY_DIM;
mediaviewFileRedCornerFg: GB_RED;
mediaviewFileYellowCornerFg: GB_YELLOW;
mediaviewFileGreenCornerFg: GB_GREEN;
mediaviewFileBlueCornerFg: GB_BLUE;
mediaviewFileExtFg: GB_BG_HARD;
videoPlayIconBg: #1d2021cc;
videoPlayIconFg: GB_FG_BRIGHT;
youtubePlayIconBg: GB_RED;
youtubePlayIconFg: GB_BG_HARD;

// Status, calls and notifications.
profileStatusFgOver: GB_AQUA;
profileVerifiedCheckBg: GB_BLUE;
profileVerifiedCheckFg: GB_BG_HARD;
callAnswerBg: GB_GREEN;
callAnswerBgOver: GB_AQUA;
callAnswerBgRipple: GB_BG_MUTED;
callAnswerFg: GB_BG_HARD;
callHangupBg: GB_RED;
callHangupBgOver: GB_ORANGE;
callHangupBgRipple: GB_BG_MUTED;
callHangupFg: GB_BG_HARD;
callBg: GB_BG_HARD;
callNameFg: GB_FG_BRIGHT;
callStatusFg: GB_GRAY_DIM;
callIconFg: GB_FG_UI;
callIconFgOver: GB_FG_BRIGHT;
callIconFgActive: GB_YELLOW;

toastBg: #1d2021e8;
toastFg: GB_FG_UI;
reportSpamBg: GB_BG_ALT;
reportSpamFg: GB_RED;
notificationSampleUserpicFg: GB_BG_HARD;
notificationSampleCloseFg: GB_GRAY_DIM;
notificationSampleTextFg: GB_FG;
notificationSampleNameFg: GB_FG_UI;

// Main menu.
mainMenuBg: GB_BG;
mainMenuCoverBg: GB_BG_ALT;
mainMenuCoverFg: GB_FG_UI;
mainMenuCloudFg: GB_BLUE;
mainMenuCloudBg: GB_BG_SOFT;
mainMenuCloudBgOver: GB_BG_HOVER;
mainMenuCloudBgRipple: GB_BG_MUTED;

// Selection/check states.
overviewCheckBg: GB_BG_MUTED;
overviewCheckFg: GB_FG_UI;
overviewCheckBgActive: GB_YELLOW;
overviewCheckFgActive: GB_BG_HARD;
overviewPhotoSelectOverlay: #d8a65740;

// Generic scrollbars.
scrollBarBg: #a8998466;
scrollBarBgOver: #d4be9899;
scrollBg: #1d202100;
scrollBgOver: #50494555;
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated theme is stale")
    parser.add_argument("--stdout", action="store_true", help="print the generated theme instead of writing it")
    args = parser.parse_args()

    content = render(load_colors())
    if args.stdout:
        print(content, end="")
        return 0

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            print(f"stale generated Telegram theme: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
